spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  application:
    name: my-select-shop

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


naver:
  client:
    id: dFk8xhy076ULcflQdF8l
    secret: 9mr3RhaEPY

kakao:
  restApiKey: d0fc91228613a4484fb3a76d45a74f92

host: http://ec2-43-202-3-191:ap-northeast-2:compute:amazonaws:com:8080