name: CI/CD for Spring Boot Application


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: copy jar to server
        uses: appleboy/scp-action@master
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ubuntu
         key: ${{ secrets.SSH_KEY }}
         port: 22
         source: "./build/libs/*.jar"
         target: "~"
         strip_components: 2

      - name: SSH Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            # Docker 이미지 빌드
            docker build -t myapp .

            # 기존 컨테이너 종료 및 삭제
            if [ "$(docker ps -q -f name=myapp)" ]; then
              docker stop myapp
              docker rm myapp
            fi

            # 새로운 컨테이너 실행
            docker run -d --name myapp -p 80:80 myapp
